# Generated by Django 5.2.2 on 2025-06-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_prescriptionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmodel',
            name='patient_name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
