# Generated by Django 5.2.2 on 2025-06-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_prescriptionmodel_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
