# Generated by Django 5.2.2 on 2025-06-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_alter_prescriptionmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('test_name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='lab_report')),
            ],
        ),
    ]
