# Generated by Django 5.2.2 on 2025-06-23 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
        ('patientapp', '0005_labreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('token', models.IntegerField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.doctormodel')),
                ('pt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patientmodel')),
            ],
        ),
    ]
