# Generated by Django 5.2.2 on 2025-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_bookappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='date',
            field=models.DateField(),
        ),
    ]
