# Generated by Django 5.2.2 on 2025-06-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacistapp', '0001_initial'),
    ]

    operations = [
    ]
