# Generated by Django 5.2.2 on 2025-06-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacistapp', '0002_force_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineavailability',
            name='slug',
        ),
    ]
