# Generated by Django 5.2.2 on 2025-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacistapp', '0003_remove_medicineavailability_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineavailability',
            name='medicine_code',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
