# Generated by Django 5.2.2 on 2025-06-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacistapp', '0004_medicineavailability_medicine_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllottedOrNotMedcine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('allotted_medicines', models.ManyToManyField(blank=True, related_name='allotted_to', to='pharmacistapp.medicineavailability')),
                ('not_allotted_medicines', models.ManyToManyField(blank=True, related_name='not_allotted_to', to='pharmacistapp.medicineavailability')),
            ],
        ),
    ]
