# Generated by Django 5.2.2 on 2025-06-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='available_time',
            field=models.CharField(default='09.00 am - 01.00pm', max_length=100),
        ),
    ]
